apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
      version: v1
  template:
    metadata:
      labels:
        app: todo-app
        version: v1
    spec:
      containers:
        - name: todo-app
          image: 474872686388.dkr.ecr.us-east-1.amazonaws.com/todo-app:v1
          ports:
            - containerPort: 3000
