apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
      version: v2
  template:
    metadata:
      labels:
        app: todo-app
        version: v2
    spec:
      containers:
        - name: todo-app
          image: 474872686388.dkr.ecr.us-east-1.amazonaws.com/todo-app:v2
          ports:
            - containerPort: 3000
