apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: todo-alerts
  namespace: default
spec:
  groups:
    - name: todo-alerts
      rules:
        - alert: HighCPUUsage
          expr: rate(container_cpu_usage_seconds_total{pod=~"todo-app.*"}[1m]) > 0.5
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage in Todo App"
